// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: mtpservice.proto

package mtpservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to send a message to an agent
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                              // Target agent endpoint ID
	UspMessage    []byte                 `protobuf:"bytes,2,opt,name=usp_message,json=uspMessage,proto3" json:"usp_message,omitempty"`                                                     // USP message data to send
	TransportType string                 `protobuf:"bytes,3,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`                                            // Transport type (WebSocket, MQTT, STOMP, UDS)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_mtpservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMessageRequest) GetUspMessage() []byte {
	if x != nil {
		return x.UspMessage
	}
	return nil
}

func (x *SendMessageRequest) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *SendMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response from sending message to agent
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                 // Whether message was sent successfully
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`    // Error message if sending failed
	TransportUsed string                 `protobuf:"bytes,3,opt,name=transport_used,json=transportUsed,proto3" json:"transport_used,omitempty"` // Transport type actually used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_mtpservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SendMessageResponse) GetTransportUsed() string {
	if x != nil {
		return x.TransportUsed
	}
	return ""
}

// Request to get connected agents
type GetConnectedAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType string                 `protobuf:"bytes,1,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"` // Filter by transport type (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedAgentsRequest) Reset() {
	*x = GetConnectedAgentsRequest{}
	mi := &file_mtpservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedAgentsRequest) ProtoMessage() {}

func (x *GetConnectedAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectedAgentsRequest) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectedAgentsRequest) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

// Response with connected agents
type GetConnectedAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*ConnectedAgent      `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedAgentsResponse) Reset() {
	*x = GetConnectedAgentsResponse{}
	mi := &file_mtpservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedAgentsResponse) ProtoMessage() {}

func (x *GetConnectedAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectedAgentsResponse) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectedAgentsResponse) GetAgents() []*ConnectedAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// Information about a connected agent
type ConnectedAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                   // Agent endpoint ID
	TransportType string                 `protobuf:"bytes,2,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"` // Transport type being used
	ConnectedAt   int64                  `protobuf:"varint,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`      // Connection timestamp
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                // Internal client ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedAgent) Reset() {
	*x = ConnectedAgent{}
	mi := &file_mtpservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedAgent) ProtoMessage() {}

func (x *ConnectedAgent) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedAgent.ProtoReflect.Descriptor instead.
func (*ConnectedAgent) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectedAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectedAgent) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *ConnectedAgent) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *ConnectedAgent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_mtpservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{5}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`        // "healthy" or "unhealthy"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // Additional health information
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Health check timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_mtpservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtpservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_mtpservice_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_mtpservice_proto protoreflect.FileDescriptor

const file_mtpservice_proto_rawDesc = "" +
	"\n" +
	"\x10mtpservice.proto\x12\n" +
	"mtpservice\"\xfe\x01\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vusp_message\x18\x02 \x01(\fR\n" +
	"uspMessage\x12%\n" +
	"\x0etransport_type\x18\x03 \x01(\tR\rtransportType\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.mtpservice.SendMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0etransport_used\x18\x03 \x01(\tR\rtransportUsed\"B\n" +
	"\x19GetConnectedAgentsRequest\x12%\n" +
	"\x0etransport_type\x18\x01 \x01(\tR\rtransportType\"P\n" +
	"\x1aGetConnectedAgentsResponse\x122\n" +
	"\x06agents\x18\x01 \x03(\v2\x1a.mtpservice.ConnectedAgentR\x06agents\"\x92\x01\n" +
	"\x0eConnectedAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0etransport_type\x18\x02 \x01(\tR\rtransportType\x12!\n" +
	"\fconnected_at\x18\x03 \x01(\x03R\vconnectedAt\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x93\x02\n" +
	"\n" +
	"MTPService\x12U\n" +
	"\x12SendMessageToAgent\x12\x1e.mtpservice.SendMessageRequest\x1a\x1f.mtpservice.SendMessageResponse\x12c\n" +
	"\x12GetConnectedAgents\x12%.mtpservice.GetConnectedAgentsRequest\x1a&.mtpservice.GetConnectedAgentsResponse\x12I\n" +
	"\x10GetServiceHealth\x12\x19.mtpservice.HealthRequest\x1a\x1a.mtpservice.HealthResponseB\x1eZ\x1copenusp/pkg/proto/mtpserviceb\x06proto3"

var (
	file_mtpservice_proto_rawDescOnce sync.Once
	file_mtpservice_proto_rawDescData []byte
)

func file_mtpservice_proto_rawDescGZIP() []byte {
	file_mtpservice_proto_rawDescOnce.Do(func() {
		file_mtpservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mtpservice_proto_rawDesc), len(file_mtpservice_proto_rawDesc)))
	})
	return file_mtpservice_proto_rawDescData
}

var file_mtpservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mtpservice_proto_goTypes = []any{
	(*SendMessageRequest)(nil),         // 0: mtpservice.SendMessageRequest
	(*SendMessageResponse)(nil),        // 1: mtpservice.SendMessageResponse
	(*GetConnectedAgentsRequest)(nil),  // 2: mtpservice.GetConnectedAgentsRequest
	(*GetConnectedAgentsResponse)(nil), // 3: mtpservice.GetConnectedAgentsResponse
	(*ConnectedAgent)(nil),             // 4: mtpservice.ConnectedAgent
	(*HealthRequest)(nil),              // 5: mtpservice.HealthRequest
	(*HealthResponse)(nil),             // 6: mtpservice.HealthResponse
	nil,                                // 7: mtpservice.SendMessageRequest.MetadataEntry
}
var file_mtpservice_proto_depIdxs = []int32{
	7, // 0: mtpservice.SendMessageRequest.metadata:type_name -> mtpservice.SendMessageRequest.MetadataEntry
	4, // 1: mtpservice.GetConnectedAgentsResponse.agents:type_name -> mtpservice.ConnectedAgent
	0, // 2: mtpservice.MTPService.SendMessageToAgent:input_type -> mtpservice.SendMessageRequest
	2, // 3: mtpservice.MTPService.GetConnectedAgents:input_type -> mtpservice.GetConnectedAgentsRequest
	5, // 4: mtpservice.MTPService.GetServiceHealth:input_type -> mtpservice.HealthRequest
	1, // 5: mtpservice.MTPService.SendMessageToAgent:output_type -> mtpservice.SendMessageResponse
	3, // 6: mtpservice.MTPService.GetConnectedAgents:output_type -> mtpservice.GetConnectedAgentsResponse
	6, // 7: mtpservice.MTPService.GetServiceHealth:output_type -> mtpservice.HealthResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mtpservice_proto_init() }
func file_mtpservice_proto_init() {
	if File_mtpservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mtpservice_proto_rawDesc), len(file_mtpservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mtpservice_proto_goTypes,
		DependencyIndexes: file_mtpservice_proto_depIdxs,
		MessageInfos:      file_mtpservice_proto_msgTypes,
	}.Build()
	File_mtpservice_proto = out.File
	file_mtpservice_proto_goTypes = nil
	file_mtpservice_proto_depIdxs = nil
}
