// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: mtpservice.proto

package mtpservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MTPService_SendMessageToAgent_FullMethodName = "/mtpservice.MTPService/SendMessageToAgent"
	MTPService_GetConnectedAgents_FullMethodName = "/mtpservice.MTPService/GetConnectedAgents"
	MTPService_GetServiceHealth_FullMethodName   = "/mtpservice.MTPService/GetServiceHealth"
)

// MTPServiceClient is the client API for MTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MTP Service provides message transport protocol functionality
type MTPServiceClient interface {
	// SendMessageToAgent sends a USP message to a specific agent via the appropriate transport
	SendMessageToAgent(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// GetConnectedAgents returns a list of currently connected agents
	GetConnectedAgents(ctx context.Context, in *GetConnectedAgentsRequest, opts ...grpc.CallOption) (*GetConnectedAgentsResponse, error)
	// GetServiceHealth returns the health status of the MTP service
	GetServiceHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mTPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMTPServiceClient(cc grpc.ClientConnInterface) MTPServiceClient {
	return &mTPServiceClient{cc}
}

func (c *mTPServiceClient) SendMessageToAgent(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, MTPService_SendMessageToAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTPServiceClient) GetConnectedAgents(ctx context.Context, in *GetConnectedAgentsRequest, opts ...grpc.CallOption) (*GetConnectedAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectedAgentsResponse)
	err := c.cc.Invoke(ctx, MTPService_GetConnectedAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTPServiceClient) GetServiceHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MTPService_GetServiceHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTPServiceServer is the server API for MTPService service.
// All implementations must embed UnimplementedMTPServiceServer
// for forward compatibility.
//
// MTP Service provides message transport protocol functionality
type MTPServiceServer interface {
	// SendMessageToAgent sends a USP message to a specific agent via the appropriate transport
	SendMessageToAgent(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// GetConnectedAgents returns a list of currently connected agents
	GetConnectedAgents(context.Context, *GetConnectedAgentsRequest) (*GetConnectedAgentsResponse, error)
	// GetServiceHealth returns the health status of the MTP service
	GetServiceHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMTPServiceServer()
}

// UnimplementedMTPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMTPServiceServer struct{}

func (UnimplementedMTPServiceServer) SendMessageToAgent(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToAgent not implemented")
}
func (UnimplementedMTPServiceServer) GetConnectedAgents(context.Context, *GetConnectedAgentsRequest) (*GetConnectedAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectedAgents not implemented")
}
func (UnimplementedMTPServiceServer) GetServiceHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceHealth not implemented")
}
func (UnimplementedMTPServiceServer) mustEmbedUnimplementedMTPServiceServer() {}
func (UnimplementedMTPServiceServer) testEmbeddedByValue()                    {}

// UnsafeMTPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MTPServiceServer will
// result in compilation errors.
type UnsafeMTPServiceServer interface {
	mustEmbedUnimplementedMTPServiceServer()
}

func RegisterMTPServiceServer(s grpc.ServiceRegistrar, srv MTPServiceServer) {
	// If the following call pancis, it indicates UnimplementedMTPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MTPService_ServiceDesc, srv)
}

func _MTPService_SendMessageToAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTPServiceServer).SendMessageToAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTPService_SendMessageToAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTPServiceServer).SendMessageToAgent(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTPService_GetConnectedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTPServiceServer).GetConnectedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTPService_GetConnectedAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTPServiceServer).GetConnectedAgents(ctx, req.(*GetConnectedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTPService_GetServiceHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTPServiceServer).GetServiceHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTPService_GetServiceHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTPServiceServer).GetServiceHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MTPService_ServiceDesc is the grpc.ServiceDesc for MTPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MTPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtpservice.MTPService",
	HandlerType: (*MTPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageToAgent",
			Handler:    _MTPService_SendMessageToAgent_Handler,
		},
		{
			MethodName: "GetConnectedAgents",
			Handler:    _MTPService_GetConnectedAgents_Handler,
		},
		{
			MethodName: "GetServiceHealth",
			Handler:    _MTPService_GetServiceHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtpservice.proto",
}
