// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pkg/proto/uspservice/uspservice.proto

package uspservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	USPService_ProcessUSPMessage_FullMethodName         = "/uspservice.USPService/ProcessUSPMessage"
	USPService_HandleProactiveOnboarding_FullMethodName = "/uspservice.USPService/HandleProactiveOnboarding"
	USPService_GetServiceHealth_FullMethodName          = "/uspservice.USPService/GetServiceHealth"
	USPService_GetServiceStatus_FullMethodName          = "/uspservice.USPService/GetServiceStatus"
)

// USPServiceClient is the client API for USPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// USP Service provides TR-369 protocol processing and device management
type USPServiceClient interface {
	// ProcessUSPMessage processes incoming USP messages and returns responses
	ProcessUSPMessage(ctx context.Context, in *USPMessageRequest, opts ...grpc.CallOption) (*USPMessageResponse, error)
	// HandleProactiveOnboarding handles TR-369 proactive onboarding when MTP connection succeeds
	HandleProactiveOnboarding(ctx context.Context, in *ProactiveOnboardingRequest, opts ...grpc.CallOption) (*ProactiveOnboardingResponse, error)
	// GetServiceHealth returns the health status of the USP service
	GetServiceHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetServiceStatus returns detailed status information
	GetServiceStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type uSPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUSPServiceClient(cc grpc.ClientConnInterface) USPServiceClient {
	return &uSPServiceClient{cc}
}

func (c *uSPServiceClient) ProcessUSPMessage(ctx context.Context, in *USPMessageRequest, opts ...grpc.CallOption) (*USPMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(USPMessageResponse)
	err := c.cc.Invoke(ctx, USPService_ProcessUSPMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSPServiceClient) HandleProactiveOnboarding(ctx context.Context, in *ProactiveOnboardingRequest, opts ...grpc.CallOption) (*ProactiveOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProactiveOnboardingResponse)
	err := c.cc.Invoke(ctx, USPService_HandleProactiveOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSPServiceClient) GetServiceHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, USPService_GetServiceHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSPServiceClient) GetServiceStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, USPService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// USPServiceServer is the server API for USPService service.
// All implementations must embed UnimplementedUSPServiceServer
// for forward compatibility.
//
// USP Service provides TR-369 protocol processing and device management
type USPServiceServer interface {
	// ProcessUSPMessage processes incoming USP messages and returns responses
	ProcessUSPMessage(context.Context, *USPMessageRequest) (*USPMessageResponse, error)
	// HandleProactiveOnboarding handles TR-369 proactive onboarding when MTP connection succeeds
	HandleProactiveOnboarding(context.Context, *ProactiveOnboardingRequest) (*ProactiveOnboardingResponse, error)
	// GetServiceHealth returns the health status of the USP service
	GetServiceHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetServiceStatus returns detailed status information
	GetServiceStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedUSPServiceServer()
}

// UnimplementedUSPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUSPServiceServer struct{}

func (UnimplementedUSPServiceServer) ProcessUSPMessage(context.Context, *USPMessageRequest) (*USPMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessUSPMessage not implemented")
}
func (UnimplementedUSPServiceServer) HandleProactiveOnboarding(context.Context, *ProactiveOnboardingRequest) (*ProactiveOnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleProactiveOnboarding not implemented")
}
func (UnimplementedUSPServiceServer) GetServiceHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceHealth not implemented")
}
func (UnimplementedUSPServiceServer) GetServiceStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedUSPServiceServer) mustEmbedUnimplementedUSPServiceServer() {}
func (UnimplementedUSPServiceServer) testEmbeddedByValue()                    {}

// UnsafeUSPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to USPServiceServer will
// result in compilation errors.
type UnsafeUSPServiceServer interface {
	mustEmbedUnimplementedUSPServiceServer()
}

func RegisterUSPServiceServer(s grpc.ServiceRegistrar, srv USPServiceServer) {
	// If the following call pancis, it indicates UnimplementedUSPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&USPService_ServiceDesc, srv)
}

func _USPService_ProcessUSPMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(USPMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USPServiceServer).ProcessUSPMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USPService_ProcessUSPMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USPServiceServer).ProcessUSPMessage(ctx, req.(*USPMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USPService_HandleProactiveOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProactiveOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USPServiceServer).HandleProactiveOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USPService_HandleProactiveOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USPServiceServer).HandleProactiveOnboarding(ctx, req.(*ProactiveOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USPService_GetServiceHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USPServiceServer).GetServiceHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USPService_GetServiceHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USPServiceServer).GetServiceHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USPService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USPServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USPService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USPServiceServer).GetServiceStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// USPService_ServiceDesc is the grpc.ServiceDesc for USPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var USPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uspservice.USPService",
	HandlerType: (*USPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessUSPMessage",
			Handler:    _USPService_ProcessUSPMessage_Handler,
		},
		{
			MethodName: "HandleProactiveOnboarding",
			Handler:    _USPService_HandleProactiveOnboarding_Handler,
		},
		{
			MethodName: "GetServiceHealth",
			Handler:    _USPService_GetServiceHealth_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _USPService_GetServiceStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/uspservice/uspservice.proto",
}
