// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/proto/uspservice/uspservice.proto

package uspservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to process a USP message
type USPMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UspData       []byte                 `protobuf:"bytes,1,opt,name=usp_data,json=uspData,proto3" json:"usp_data,omitempty"`                                                              // Raw USP record data
	TransportType string                 `protobuf:"bytes,2,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`                                            // Transport type (WebSocket, MQTT, STOMP, etc.)
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                           // Client identifier from MTP service
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // Message timestamp
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata from transport
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *USPMessageRequest) Reset() {
	*x = USPMessageRequest{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USPMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USPMessageRequest) ProtoMessage() {}

func (x *USPMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USPMessageRequest.ProtoReflect.Descriptor instead.
func (*USPMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{0}
}

func (x *USPMessageRequest) GetUspData() []byte {
	if x != nil {
		return x.UspData
	}
	return nil
}

func (x *USPMessageRequest) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *USPMessageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *USPMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *USPMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response from USP message processing
type USPMessageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponseData    []byte                 `protobuf:"bytes,1,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`           // Raw USP response record data
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                           // Processing status (success, error, etc.)
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`           // Error message if processing failed
	DeviceInfo      *DeviceInfo            `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`                 // Device information if onboarding occurred
	DeviceOnboarded bool                   `protobuf:"varint,5,opt,name=device_onboarded,json=deviceOnboarded,proto3" json:"device_onboarded,omitempty"` // True if device was onboarded
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *USPMessageResponse) Reset() {
	*x = USPMessageResponse{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USPMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USPMessageResponse) ProtoMessage() {}

func (x *USPMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USPMessageResponse.ProtoReflect.Descriptor instead.
func (*USPMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{1}
}

func (x *USPMessageResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

func (x *USPMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *USPMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *USPMessageResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *USPMessageResponse) GetDeviceOnboarded() bool {
	if x != nil {
		return x.DeviceOnboarded
	}
	return false
}

// Device information extracted during onboarding
type DeviceInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	EndpointId                string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ProductClass              string                 `protobuf:"bytes,2,opt,name=product_class,json=productClass,proto3" json:"product_class,omitempty"`
	SerialNumber              string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Manufacturer              string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ModelName                 string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	SoftwareVersion           string                 `protobuf:"bytes,6,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	HardwareVersion           string                 `protobuf:"bytes,7,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SupportedProtocolVersions string                 `protobuf:"bytes,8,opt,name=supported_protocol_versions,json=supportedProtocolVersions,proto3" json:"supported_protocol_versions,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInfo) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *DeviceInfo) GetProductClass() string {
	if x != nil {
		return x.ProductClass
	}
	return ""
}

func (x *DeviceInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *DeviceInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *DeviceInfo) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetSupportedProtocolVersions() string {
	if x != nil {
		return x.SupportedProtocolVersions
	}
	return ""
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{3}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`        // "healthy" or "unhealthy"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // Additional health information
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Health check timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Status request
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{5}
}

// Status response
type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime            string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	ProcessedMessages int32                  `protobuf:"varint,4,opt,name=processed_messages,json=processedMessages,proto3" json:"processed_messages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatusResponse) GetProcessedMessages() int32 {
	if x != nil {
		return x.ProcessedMessages
	}
	return 0
}

// Request for TR-369 proactive onboarding when MTP connection succeeds but no USP messages received
type ProactiveOnboardingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EndpointId        string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`                                                                                                // Generated endpoint ID for proactive onboarding
	UspVersion        string                 `protobuf:"bytes,2,opt,name=usp_version,json=uspVersion,proto3" json:"usp_version,omitempty"`                                                                                                // USP protocol version to use (1.3 or 1.4)
	ConnectionContext map[string]string      `protobuf:"bytes,3,rep,name=connection_context,json=connectionContext,proto3" json:"connection_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // MTP connection context information
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProactiveOnboardingRequest) Reset() {
	*x = ProactiveOnboardingRequest{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProactiveOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProactiveOnboardingRequest) ProtoMessage() {}

func (x *ProactiveOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProactiveOnboardingRequest.ProtoReflect.Descriptor instead.
func (*ProactiveOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{7}
}

func (x *ProactiveOnboardingRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ProactiveOnboardingRequest) GetUspVersion() string {
	if x != nil {
		return x.UspVersion
	}
	return ""
}

func (x *ProactiveOnboardingRequest) GetConnectionContext() map[string]string {
	if x != nil {
		return x.ConnectionContext
	}
	return nil
}

// Response from proactive onboarding handling
type ProactiveOnboardingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                          // True if proactive onboarding was initiated
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                           // Status message or error description
	OnboardingStatus string                 `protobuf:"bytes,3,opt,name=onboarding_status,json=onboardingStatus,proto3" json:"onboarding_status,omitempty"` // Current onboarding status
	AgentId          string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                            // Agent ID being onboarded
	OnboardedDevices int32                  `protobuf:"varint,5,opt,name=onboarded_devices,json=onboardedDevices,proto3" json:"onboarded_devices,omitempty"`
	Statistics       map[string]string      `protobuf:"bytes,6,rep,name=statistics,proto3" json:"statistics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProactiveOnboardingResponse) Reset() {
	*x = ProactiveOnboardingResponse{}
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProactiveOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProactiveOnboardingResponse) ProtoMessage() {}

func (x *ProactiveOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_uspservice_uspservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProactiveOnboardingResponse.ProtoReflect.Descriptor instead.
func (*ProactiveOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP(), []int{8}
}

func (x *ProactiveOnboardingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProactiveOnboardingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProactiveOnboardingResponse) GetOnboardingStatus() string {
	if x != nil {
		return x.OnboardingStatus
	}
	return ""
}

func (x *ProactiveOnboardingResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProactiveOnboardingResponse) GetOnboardedDevices() int32 {
	if x != nil {
		return x.OnboardedDevices
	}
	return 0
}

func (x *ProactiveOnboardingResponse) GetStatistics() map[string]string {
	if x != nil {
		return x.Statistics
	}
	return nil
}

var File_pkg_proto_uspservice_uspservice_proto protoreflect.FileDescriptor

const file_pkg_proto_uspservice_uspservice_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/uspservice/uspservice.proto\x12\n" +
	"uspservice\"\x96\x02\n" +
	"\x11USPMessageRequest\x12\x19\n" +
	"\busp_data\x18\x01 \x01(\fR\auspData\x12%\n" +
	"\x0etransport_type\x18\x02 \x01(\tR\rtransportType\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.uspservice.USPMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x12USPMessageResponse\x12#\n" +
	"\rresponse_data\x18\x01 \x01(\fR\fresponseData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x127\n" +
	"\vdevice_info\x18\x04 \x01(\v2\x16.uspservice.DeviceInfoR\n" +
	"deviceInfo\x12)\n" +
	"\x10device_onboarded\x18\x05 \x01(\bR\x0fdeviceOnboarded\"\xd0\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rproduct_class\x18\x02 \x01(\tR\fproductClass\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12)\n" +
	"\x10software_version\x18\x06 \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10hardware_version\x18\a \x01(\tR\x0fhardwareVersion\x12>\n" +
	"\x1bsupported_protocol_versions\x18\b \x01(\tR\x19supportedProtocolVersions\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x0f\n" +
	"\rStatusRequest\"\x94\x01\n" +
	"\x0eStatusResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\x12-\n" +
	"\x12processed_messages\x18\x04 \x01(\x05R\x11processedMessages\"\x92\x02\n" +
	"\x1aProactiveOnboardingRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1f\n" +
	"\vusp_version\x18\x02 \x01(\tR\n" +
	"uspVersion\x12l\n" +
	"\x12connection_context\x18\x03 \x03(\v2=.uspservice.ProactiveOnboardingRequest.ConnectionContextEntryR\x11connectionContext\x1aD\n" +
	"\x16ConnectionContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x02\n" +
	"\x1bProactiveOnboardingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11onboarding_status\x18\x03 \x01(\tR\x10onboardingStatus\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12+\n" +
	"\x11onboarded_devices\x18\x05 \x01(\x05R\x10onboardedDevices\x12W\n" +
	"\n" +
	"statistics\x18\x06 \x03(\v27.uspservice.ProactiveOnboardingResponse.StatisticsEntryR\n" +
	"statistics\x1a=\n" +
	"\x0fStatisticsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe4\x02\n" +
	"\n" +
	"USPService\x12R\n" +
	"\x11ProcessUSPMessage\x12\x1d.uspservice.USPMessageRequest\x1a\x1e.uspservice.USPMessageResponse\x12l\n" +
	"\x19HandleProactiveOnboarding\x12&.uspservice.ProactiveOnboardingRequest\x1a'.uspservice.ProactiveOnboardingResponse\x12I\n" +
	"\x10GetServiceHealth\x12\x19.uspservice.HealthRequest\x1a\x1a.uspservice.HealthResponse\x12I\n" +
	"\x10GetServiceStatus\x12\x19.uspservice.StatusRequest\x1a\x1a.uspservice.StatusResponseB\x1eZ\x1copenusp/pkg/proto/uspserviceb\x06proto3"

var (
	file_pkg_proto_uspservice_uspservice_proto_rawDescOnce sync.Once
	file_pkg_proto_uspservice_uspservice_proto_rawDescData []byte
)

func file_pkg_proto_uspservice_uspservice_proto_rawDescGZIP() []byte {
	file_pkg_proto_uspservice_uspservice_proto_rawDescOnce.Do(func() {
		file_pkg_proto_uspservice_uspservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_uspservice_uspservice_proto_rawDesc), len(file_pkg_proto_uspservice_uspservice_proto_rawDesc)))
	})
	return file_pkg_proto_uspservice_uspservice_proto_rawDescData
}

var file_pkg_proto_uspservice_uspservice_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_uspservice_uspservice_proto_goTypes = []any{
	(*USPMessageRequest)(nil),           // 0: uspservice.USPMessageRequest
	(*USPMessageResponse)(nil),          // 1: uspservice.USPMessageResponse
	(*DeviceInfo)(nil),                  // 2: uspservice.DeviceInfo
	(*HealthRequest)(nil),               // 3: uspservice.HealthRequest
	(*HealthResponse)(nil),              // 4: uspservice.HealthResponse
	(*StatusRequest)(nil),               // 5: uspservice.StatusRequest
	(*StatusResponse)(nil),              // 6: uspservice.StatusResponse
	(*ProactiveOnboardingRequest)(nil),  // 7: uspservice.ProactiveOnboardingRequest
	(*ProactiveOnboardingResponse)(nil), // 8: uspservice.ProactiveOnboardingResponse
	nil,                                 // 9: uspservice.USPMessageRequest.MetadataEntry
	nil,                                 // 10: uspservice.ProactiveOnboardingRequest.ConnectionContextEntry
	nil,                                 // 11: uspservice.ProactiveOnboardingResponse.StatisticsEntry
}
var file_pkg_proto_uspservice_uspservice_proto_depIdxs = []int32{
	9,  // 0: uspservice.USPMessageRequest.metadata:type_name -> uspservice.USPMessageRequest.MetadataEntry
	2,  // 1: uspservice.USPMessageResponse.device_info:type_name -> uspservice.DeviceInfo
	10, // 2: uspservice.ProactiveOnboardingRequest.connection_context:type_name -> uspservice.ProactiveOnboardingRequest.ConnectionContextEntry
	11, // 3: uspservice.ProactiveOnboardingResponse.statistics:type_name -> uspservice.ProactiveOnboardingResponse.StatisticsEntry
	0,  // 4: uspservice.USPService.ProcessUSPMessage:input_type -> uspservice.USPMessageRequest
	7,  // 5: uspservice.USPService.HandleProactiveOnboarding:input_type -> uspservice.ProactiveOnboardingRequest
	3,  // 6: uspservice.USPService.GetServiceHealth:input_type -> uspservice.HealthRequest
	5,  // 7: uspservice.USPService.GetServiceStatus:input_type -> uspservice.StatusRequest
	1,  // 8: uspservice.USPService.ProcessUSPMessage:output_type -> uspservice.USPMessageResponse
	8,  // 9: uspservice.USPService.HandleProactiveOnboarding:output_type -> uspservice.ProactiveOnboardingResponse
	4,  // 10: uspservice.USPService.GetServiceHealth:output_type -> uspservice.HealthResponse
	6,  // 11: uspservice.USPService.GetServiceStatus:output_type -> uspservice.StatusResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_uspservice_uspservice_proto_init() }
func file_pkg_proto_uspservice_uspservice_proto_init() {
	if File_pkg_proto_uspservice_uspservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_uspservice_uspservice_proto_rawDesc), len(file_pkg_proto_uspservice_uspservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_uspservice_uspservice_proto_goTypes,
		DependencyIndexes: file_pkg_proto_uspservice_uspservice_proto_depIdxs,
		MessageInfos:      file_pkg_proto_uspservice_uspservice_proto_msgTypes,
	}.Build()
	File_pkg_proto_uspservice_uspservice_proto = out.File
	file_pkg_proto_uspservice_uspservice_proto_goTypes = nil
	file_pkg_proto_uspservice_uspservice_proto_depIdxs = nil
}
