// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/proto/dataservice/dataservice.proto

package dataservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device message
type Device struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId      string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ProductClass    string                 `protobuf:"bytes,3,opt,name=product_class,json=productClass,proto3" json:"product_class,omitempty"`
	Manufacturer    string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ModelName       string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	SerialNumber    string                 `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,7,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,8,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IpAddress       string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ConnectionType  string                 `protobuf:"bytes,12,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Device) GetProductClass() string {
	if x != nil {
		return x.ProductClass
	}
	return ""
}

func (x *Device) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Device) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Device) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Device) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *Device) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Device) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Device) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Device) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Parameter message
type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Writable      bool                   `protobuf:"varint,6,opt,name=writable,proto3" json:"writable,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{1}
}

func (x *Parameter) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parameter) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Parameter) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Parameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *Parameter) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Parameter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Parameter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Alert message
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Severity      int32                  `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Resolved      bool                   `protobuf:"varint,7,opt,name=resolved,proto3" json:"resolved,omitempty"`
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Alert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Alert) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *Alert) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Session message
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	MessageCount  int32                  `protobuf:"varint,9,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Session) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *Session) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages for Device operations
type CreateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDeviceRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type CreateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceResponse) Reset() {
	*x = CreateDeviceResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceResponse) ProtoMessage() {}

func (x *CreateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeviceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceByEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByEndpointRequest) Reset() {
	*x = GetDeviceByEndpointRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByEndpointRequest) ProtoMessage() {}

func (x *GetDeviceByEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceByEndpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceByEndpointRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type GetDeviceByEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByEndpointResponse) Reset() {
	*x = GetDeviceByEndpointResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByEndpointResponse) ProtoMessage() {}

func (x *GetDeviceByEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceByEndpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceByEndpointResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDevicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{11}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ListDevicesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDeviceRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDeviceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceResponse) Reset() {
	*x = DeleteDeviceResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceResponse) ProtoMessage() {}

func (x *DeleteDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request/Response messages for Parameter operations
type CreateParameterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     *Parameter             `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParameterRequest) Reset() {
	*x = CreateParameterRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParameterRequest) ProtoMessage() {}

func (x *CreateParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParameterRequest.ProtoReflect.Descriptor instead.
func (*CreateParameterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{16}
}

func (x *CreateParameterRequest) GetParameter() *Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

type CreateParameterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     *Parameter             `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParameterResponse) Reset() {
	*x = CreateParameterResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParameterResponse) ProtoMessage() {}

func (x *CreateParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParameterResponse.ProtoReflect.Descriptor instead.
func (*CreateParameterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{17}
}

func (x *CreateParameterResponse) GetParameter() *Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

type GetDeviceParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceParametersRequest) Reset() {
	*x = GetDeviceParametersRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceParametersRequest) ProtoMessage() {}

func (x *GetDeviceParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceParametersRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceParametersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{18}
}

func (x *GetDeviceParametersRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type GetDeviceParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*Parameter           `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceParametersResponse) Reset() {
	*x = GetDeviceParametersResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceParametersResponse) ProtoMessage() {}

func (x *GetDeviceParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceParametersResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceParametersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{19}
}

func (x *GetDeviceParametersResponse) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetParametersByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PathPattern   string                 `protobuf:"bytes,2,opt,name=path_pattern,json=pathPattern,proto3" json:"path_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParametersByPathRequest) Reset() {
	*x = GetParametersByPathRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParametersByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParametersByPathRequest) ProtoMessage() {}

func (x *GetParametersByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParametersByPathRequest.ProtoReflect.Descriptor instead.
func (*GetParametersByPathRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{20}
}

func (x *GetParametersByPathRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetParametersByPathRequest) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

type GetParametersByPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*Parameter           `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParametersByPathResponse) Reset() {
	*x = GetParametersByPathResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParametersByPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParametersByPathResponse) ProtoMessage() {}

func (x *GetParametersByPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParametersByPathResponse.ProtoReflect.Descriptor instead.
func (*GetParametersByPathResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{21}
}

func (x *GetParametersByPathResponse) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DeleteParameterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteParameterRequest) Reset() {
	*x = DeleteParameterRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParameterRequest) ProtoMessage() {}

func (x *DeleteParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParameterRequest.ProtoReflect.Descriptor instead.
func (*DeleteParameterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteParameterRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeleteParameterRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteParameterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteParameterResponse) Reset() {
	*x = DeleteParameterResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParameterResponse) ProtoMessage() {}

func (x *DeleteParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParameterResponse.ProtoReflect.Descriptor instead.
func (*DeleteParameterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteParameterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request/Response messages for Alert operations
type CreateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{24}
}

func (x *CreateAlertRequest) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type CreateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertResponse) Reset() {
	*x = CreateAlertResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertResponse) ProtoMessage() {}

func (x *CreateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{25}
}

func (x *CreateAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type GetDeviceAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Resolved      *bool                  `protobuf:"varint,2,opt,name=resolved,proto3,oneof" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceAlertsRequest) Reset() {
	*x = GetDeviceAlertsRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceAlertsRequest) ProtoMessage() {}

func (x *GetDeviceAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceAlertsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{26}
}

func (x *GetDeviceAlertsRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetDeviceAlertsRequest) GetResolved() bool {
	if x != nil && x.Resolved != nil {
		return *x.Resolved
	}
	return false
}

type GetDeviceAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceAlertsResponse) Reset() {
	*x = GetDeviceAlertsResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceAlertsResponse) ProtoMessage() {}

func (x *GetDeviceAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceAlertsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{27}
}

func (x *GetDeviceAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{28}
}

func (x *ListAlertsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{29}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type ResolveAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertRequest) Reset() {
	*x = ResolveAlertRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertRequest) ProtoMessage() {}

func (x *ResolveAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertRequest.ProtoReflect.Descriptor instead.
func (*ResolveAlertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{30}
}

func (x *ResolveAlertRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResolveAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertResponse) Reset() {
	*x = ResolveAlertResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertResponse) ProtoMessage() {}

func (x *ResolveAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertResponse.ProtoReflect.Descriptor instead.
func (*ResolveAlertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request/Response messages for Session operations
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{32}
}

func (x *CreateSessionRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{33}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{34}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{35}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type UpdateSessionActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionActivityRequest) Reset() {
	*x = UpdateSessionActivityRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionActivityRequest) ProtoMessage() {}

func (x *UpdateSessionActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionActivityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateSessionActivityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type UpdateSessionActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionActivityResponse) Reset() {
	*x = UpdateSessionActivityResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionActivityResponse) ProtoMessage() {}

func (x *UpdateSessionActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionActivityResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionActivityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateSessionActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{38}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{39}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDeviceSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceSessionsRequest) Reset() {
	*x = GetDeviceSessionsRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceSessionsRequest) ProtoMessage() {}

func (x *GetDeviceSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{40}
}

func (x *GetDeviceSessionsRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type GetDeviceSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceSessionsResponse) Reset() {
	*x = GetDeviceSessionsResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceSessionsResponse) ProtoMessage() {}

func (x *GetDeviceSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{41}
}

func (x *GetDeviceSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{42}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{43}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{44}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DatabaseStats map[string]string      `protobuf:"bytes,3,rep,name=database_stats,json=databaseStats,proto3" json:"database_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeviceCount   int64                  `protobuf:"varint,4,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dataservice_dataservice_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP(), []int{45}
}

func (x *GetStatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetDatabaseStats() map[string]string {
	if x != nil {
		return x.DatabaseStats
	}
	return nil
}

func (x *GetStatusResponse) GetDeviceCount() int64 {
	if x != nil {
		return x.DeviceCount
	}
	return 0
}

func (x *GetStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_proto_dataservice_dataservice_proto protoreflect.FileDescriptor

const file_pkg_proto_dataservice_dataservice_proto_rawDesc = "" +
	"\n" +
	"'pkg/proto/dataservice/dataservice.proto\x12\vdataservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x04\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rproduct_class\x18\x03 \x01(\tR\fproductClass\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12#\n" +
	"\rserial_number\x18\x06 \x01(\tR\fserialNumber\x12)\n" +
	"\x10software_version\x18\a \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10hardware_version\x18\b \x01(\tR\x0fhardwareVersion\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x127\n" +
	"\tlast_seen\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12'\n" +
	"\x0fconnection_type\x18\f \x01(\tR\x0econnectionType\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc7\x02\n" +
	"\tParameter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bwritable\x18\x06 \x01(\bR\bwritable\x12=\n" +
	"\flast_updated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\x05R\bseverity\x12\x1a\n" +
	"\bresolved\x18\a \x01(\bR\bresolved\x12;\n" +
	"\vresolved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd7\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12?\n" +
	"\rlast_activity\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12#\n" +
	"\rmessage_count\x18\t \x01(\x05R\fmessageCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\x13CreateDeviceRequest\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"C\n" +
	"\x14CreateDeviceResponse\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"@\n" +
	"\x11GetDeviceResponse\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"=\n" +
	"\x1aGetDeviceByEndpointRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"J\n" +
	"\x1bGetDeviceByEndpointResponse\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"B\n" +
	"\x12ListDevicesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Z\n" +
	"\x13ListDevicesResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.dataservice.DeviceR\adevices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x13UpdateDeviceRequest\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"C\n" +
	"\x14UpdateDeviceResponse\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.dataservice.DeviceR\x06device\"%\n" +
	"\x13DeleteDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"0\n" +
	"\x14DeleteDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x16CreateParameterRequest\x124\n" +
	"\tparameter\x18\x01 \x01(\v2\x16.dataservice.ParameterR\tparameter\"O\n" +
	"\x17CreateParameterResponse\x124\n" +
	"\tparameter\x18\x01 \x01(\v2\x16.dataservice.ParameterR\tparameter\"9\n" +
	"\x1aGetDeviceParametersRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\"U\n" +
	"\x1bGetDeviceParametersResponse\x126\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x16.dataservice.ParameterR\n" +
	"parameters\"\\\n" +
	"\x1aGetParametersByPathRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12!\n" +
	"\fpath_pattern\x18\x02 \x01(\tR\vpathPattern\"U\n" +
	"\x1bGetParametersByPathResponse\x126\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x16.dataservice.ParameterR\n" +
	"parameters\"I\n" +
	"\x16DeleteParameterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"3\n" +
	"\x17DeleteParameterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x12CreateAlertRequest\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.dataservice.AlertR\x05alert\"?\n" +
	"\x13CreateAlertResponse\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.dataservice.AlertR\x05alert\"c\n" +
	"\x16GetDeviceAlertsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x1f\n" +
	"\bresolved\x18\x02 \x01(\bH\x00R\bresolved\x88\x01\x01B\v\n" +
	"\t_resolved\"E\n" +
	"\x17GetDeviceAlertsResponse\x12*\n" +
	"\x06alerts\x18\x01 \x03(\v2\x12.dataservice.AlertR\x06alerts\"A\n" +
	"\x11ListAlertsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x12ListAlertsResponse\x12*\n" +
	"\x06alerts\x18\x01 \x03(\v2\x12.dataservice.AlertR\x06alerts\"%\n" +
	"\x13ResolveAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"0\n" +
	"\x14ResolveAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x14CreateSessionRequest\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.dataservice.SessionR\asession\"G\n" +
	"\x15CreateSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.dataservice.SessionR\asession\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"D\n" +
	"\x12GetSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.dataservice.SessionR\asession\"=\n" +
	"\x1cUpdateSessionActivityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"9\n" +
	"\x1dUpdateSessionActivityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x18GetDeviceSessionsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\"M\n" +
	"\x19GetDeviceSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.dataservice.SessionR\bsessions\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x12\n" +
	"\x10GetStatusRequest\"\xa4\x02\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12X\n" +
	"\x0edatabase_stats\x18\x03 \x03(\v21.dataservice.GetStatusResponse.DatabaseStatsEntryR\rdatabaseStats\x12!\n" +
	"\fdevice_count\x18\x04 \x01(\x03R\vdeviceCount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a@\n" +
	"\x12DatabaseStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe6\x0e\n" +
	"\vDataService\x12P\n" +
	"\vHealthCheck\x12\x1f.dataservice.HealthCheckRequest\x1a .dataservice.HealthCheckResponse\x12J\n" +
	"\tGetStatus\x12\x1d.dataservice.GetStatusRequest\x1a\x1e.dataservice.GetStatusResponse\x12S\n" +
	"\fCreateDevice\x12 .dataservice.CreateDeviceRequest\x1a!.dataservice.CreateDeviceResponse\x12J\n" +
	"\tGetDevice\x12\x1d.dataservice.GetDeviceRequest\x1a\x1e.dataservice.GetDeviceResponse\x12h\n" +
	"\x13GetDeviceByEndpoint\x12'.dataservice.GetDeviceByEndpointRequest\x1a(.dataservice.GetDeviceByEndpointResponse\x12P\n" +
	"\vListDevices\x12\x1f.dataservice.ListDevicesRequest\x1a .dataservice.ListDevicesResponse\x12S\n" +
	"\fUpdateDevice\x12 .dataservice.UpdateDeviceRequest\x1a!.dataservice.UpdateDeviceResponse\x12S\n" +
	"\fDeleteDevice\x12 .dataservice.DeleteDeviceRequest\x1a!.dataservice.DeleteDeviceResponse\x12\\\n" +
	"\x0fCreateParameter\x12#.dataservice.CreateParameterRequest\x1a$.dataservice.CreateParameterResponse\x12h\n" +
	"\x13GetDeviceParameters\x12'.dataservice.GetDeviceParametersRequest\x1a(.dataservice.GetDeviceParametersResponse\x12h\n" +
	"\x13GetParametersByPath\x12'.dataservice.GetParametersByPathRequest\x1a(.dataservice.GetParametersByPathResponse\x12\\\n" +
	"\x0fDeleteParameter\x12#.dataservice.DeleteParameterRequest\x1a$.dataservice.DeleteParameterResponse\x12P\n" +
	"\vCreateAlert\x12\x1f.dataservice.CreateAlertRequest\x1a .dataservice.CreateAlertResponse\x12\\\n" +
	"\x0fGetDeviceAlerts\x12#.dataservice.GetDeviceAlertsRequest\x1a$.dataservice.GetDeviceAlertsResponse\x12M\n" +
	"\n" +
	"ListAlerts\x12\x1e.dataservice.ListAlertsRequest\x1a\x1f.dataservice.ListAlertsResponse\x12S\n" +
	"\fResolveAlert\x12 .dataservice.ResolveAlertRequest\x1a!.dataservice.ResolveAlertResponse\x12V\n" +
	"\rCreateSession\x12!.dataservice.CreateSessionRequest\x1a\".dataservice.CreateSessionResponse\x12M\n" +
	"\n" +
	"GetSession\x12\x1e.dataservice.GetSessionRequest\x1a\x1f.dataservice.GetSessionResponse\x12n\n" +
	"\x15UpdateSessionActivity\x12).dataservice.UpdateSessionActivityRequest\x1a*.dataservice.UpdateSessionActivityResponse\x12S\n" +
	"\fCloseSession\x12 .dataservice.CloseSessionRequest\x1a!.dataservice.CloseSessionResponse\x12b\n" +
	"\x11GetDeviceSessions\x12%.dataservice.GetDeviceSessionsRequest\x1a&.dataservice.GetDeviceSessionsResponseB\x1fZ\x1dopenusp/pkg/proto/dataserviceb\x06proto3"

var (
	file_pkg_proto_dataservice_dataservice_proto_rawDescOnce sync.Once
	file_pkg_proto_dataservice_dataservice_proto_rawDescData []byte
)

func file_pkg_proto_dataservice_dataservice_proto_rawDescGZIP() []byte {
	file_pkg_proto_dataservice_dataservice_proto_rawDescOnce.Do(func() {
		file_pkg_proto_dataservice_dataservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_dataservice_dataservice_proto_rawDesc), len(file_pkg_proto_dataservice_dataservice_proto_rawDesc)))
	})
	return file_pkg_proto_dataservice_dataservice_proto_rawDescData
}

var file_pkg_proto_dataservice_dataservice_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_pkg_proto_dataservice_dataservice_proto_goTypes = []any{
	(*Device)(nil),                        // 0: dataservice.Device
	(*Parameter)(nil),                     // 1: dataservice.Parameter
	(*Alert)(nil),                         // 2: dataservice.Alert
	(*Session)(nil),                       // 3: dataservice.Session
	(*CreateDeviceRequest)(nil),           // 4: dataservice.CreateDeviceRequest
	(*CreateDeviceResponse)(nil),          // 5: dataservice.CreateDeviceResponse
	(*GetDeviceRequest)(nil),              // 6: dataservice.GetDeviceRequest
	(*GetDeviceResponse)(nil),             // 7: dataservice.GetDeviceResponse
	(*GetDeviceByEndpointRequest)(nil),    // 8: dataservice.GetDeviceByEndpointRequest
	(*GetDeviceByEndpointResponse)(nil),   // 9: dataservice.GetDeviceByEndpointResponse
	(*ListDevicesRequest)(nil),            // 10: dataservice.ListDevicesRequest
	(*ListDevicesResponse)(nil),           // 11: dataservice.ListDevicesResponse
	(*UpdateDeviceRequest)(nil),           // 12: dataservice.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil),          // 13: dataservice.UpdateDeviceResponse
	(*DeleteDeviceRequest)(nil),           // 14: dataservice.DeleteDeviceRequest
	(*DeleteDeviceResponse)(nil),          // 15: dataservice.DeleteDeviceResponse
	(*CreateParameterRequest)(nil),        // 16: dataservice.CreateParameterRequest
	(*CreateParameterResponse)(nil),       // 17: dataservice.CreateParameterResponse
	(*GetDeviceParametersRequest)(nil),    // 18: dataservice.GetDeviceParametersRequest
	(*GetDeviceParametersResponse)(nil),   // 19: dataservice.GetDeviceParametersResponse
	(*GetParametersByPathRequest)(nil),    // 20: dataservice.GetParametersByPathRequest
	(*GetParametersByPathResponse)(nil),   // 21: dataservice.GetParametersByPathResponse
	(*DeleteParameterRequest)(nil),        // 22: dataservice.DeleteParameterRequest
	(*DeleteParameterResponse)(nil),       // 23: dataservice.DeleteParameterResponse
	(*CreateAlertRequest)(nil),            // 24: dataservice.CreateAlertRequest
	(*CreateAlertResponse)(nil),           // 25: dataservice.CreateAlertResponse
	(*GetDeviceAlertsRequest)(nil),        // 26: dataservice.GetDeviceAlertsRequest
	(*GetDeviceAlertsResponse)(nil),       // 27: dataservice.GetDeviceAlertsResponse
	(*ListAlertsRequest)(nil),             // 28: dataservice.ListAlertsRequest
	(*ListAlertsResponse)(nil),            // 29: dataservice.ListAlertsResponse
	(*ResolveAlertRequest)(nil),           // 30: dataservice.ResolveAlertRequest
	(*ResolveAlertResponse)(nil),          // 31: dataservice.ResolveAlertResponse
	(*CreateSessionRequest)(nil),          // 32: dataservice.CreateSessionRequest
	(*CreateSessionResponse)(nil),         // 33: dataservice.CreateSessionResponse
	(*GetSessionRequest)(nil),             // 34: dataservice.GetSessionRequest
	(*GetSessionResponse)(nil),            // 35: dataservice.GetSessionResponse
	(*UpdateSessionActivityRequest)(nil),  // 36: dataservice.UpdateSessionActivityRequest
	(*UpdateSessionActivityResponse)(nil), // 37: dataservice.UpdateSessionActivityResponse
	(*CloseSessionRequest)(nil),           // 38: dataservice.CloseSessionRequest
	(*CloseSessionResponse)(nil),          // 39: dataservice.CloseSessionResponse
	(*GetDeviceSessionsRequest)(nil),      // 40: dataservice.GetDeviceSessionsRequest
	(*GetDeviceSessionsResponse)(nil),     // 41: dataservice.GetDeviceSessionsResponse
	(*HealthCheckRequest)(nil),            // 42: dataservice.HealthCheckRequest
	(*HealthCheckResponse)(nil),           // 43: dataservice.HealthCheckResponse
	(*GetStatusRequest)(nil),              // 44: dataservice.GetStatusRequest
	(*GetStatusResponse)(nil),             // 45: dataservice.GetStatusResponse
	nil,                                   // 46: dataservice.GetStatusResponse.DatabaseStatsEntry
	(*timestamppb.Timestamp)(nil),         // 47: google.protobuf.Timestamp
}
var file_pkg_proto_dataservice_dataservice_proto_depIdxs = []int32{
	47, // 0: dataservice.Device.last_seen:type_name -> google.protobuf.Timestamp
	47, // 1: dataservice.Device.created_at:type_name -> google.protobuf.Timestamp
	47, // 2: dataservice.Device.updated_at:type_name -> google.protobuf.Timestamp
	47, // 3: dataservice.Parameter.last_updated:type_name -> google.protobuf.Timestamp
	47, // 4: dataservice.Parameter.created_at:type_name -> google.protobuf.Timestamp
	47, // 5: dataservice.Parameter.updated_at:type_name -> google.protobuf.Timestamp
	47, // 6: dataservice.Alert.resolved_at:type_name -> google.protobuf.Timestamp
	47, // 7: dataservice.Alert.created_at:type_name -> google.protobuf.Timestamp
	47, // 8: dataservice.Alert.updated_at:type_name -> google.protobuf.Timestamp
	47, // 9: dataservice.Session.started_at:type_name -> google.protobuf.Timestamp
	47, // 10: dataservice.Session.ended_at:type_name -> google.protobuf.Timestamp
	47, // 11: dataservice.Session.last_activity:type_name -> google.protobuf.Timestamp
	47, // 12: dataservice.Session.created_at:type_name -> google.protobuf.Timestamp
	47, // 13: dataservice.Session.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 14: dataservice.CreateDeviceRequest.device:type_name -> dataservice.Device
	0,  // 15: dataservice.CreateDeviceResponse.device:type_name -> dataservice.Device
	0,  // 16: dataservice.GetDeviceResponse.device:type_name -> dataservice.Device
	0,  // 17: dataservice.GetDeviceByEndpointResponse.device:type_name -> dataservice.Device
	0,  // 18: dataservice.ListDevicesResponse.devices:type_name -> dataservice.Device
	0,  // 19: dataservice.UpdateDeviceRequest.device:type_name -> dataservice.Device
	0,  // 20: dataservice.UpdateDeviceResponse.device:type_name -> dataservice.Device
	1,  // 21: dataservice.CreateParameterRequest.parameter:type_name -> dataservice.Parameter
	1,  // 22: dataservice.CreateParameterResponse.parameter:type_name -> dataservice.Parameter
	1,  // 23: dataservice.GetDeviceParametersResponse.parameters:type_name -> dataservice.Parameter
	1,  // 24: dataservice.GetParametersByPathResponse.parameters:type_name -> dataservice.Parameter
	2,  // 25: dataservice.CreateAlertRequest.alert:type_name -> dataservice.Alert
	2,  // 26: dataservice.CreateAlertResponse.alert:type_name -> dataservice.Alert
	2,  // 27: dataservice.GetDeviceAlertsResponse.alerts:type_name -> dataservice.Alert
	2,  // 28: dataservice.ListAlertsResponse.alerts:type_name -> dataservice.Alert
	3,  // 29: dataservice.CreateSessionRequest.session:type_name -> dataservice.Session
	3,  // 30: dataservice.CreateSessionResponse.session:type_name -> dataservice.Session
	3,  // 31: dataservice.GetSessionResponse.session:type_name -> dataservice.Session
	3,  // 32: dataservice.GetDeviceSessionsResponse.sessions:type_name -> dataservice.Session
	46, // 33: dataservice.GetStatusResponse.database_stats:type_name -> dataservice.GetStatusResponse.DatabaseStatsEntry
	42, // 34: dataservice.DataService.HealthCheck:input_type -> dataservice.HealthCheckRequest
	44, // 35: dataservice.DataService.GetStatus:input_type -> dataservice.GetStatusRequest
	4,  // 36: dataservice.DataService.CreateDevice:input_type -> dataservice.CreateDeviceRequest
	6,  // 37: dataservice.DataService.GetDevice:input_type -> dataservice.GetDeviceRequest
	8,  // 38: dataservice.DataService.GetDeviceByEndpoint:input_type -> dataservice.GetDeviceByEndpointRequest
	10, // 39: dataservice.DataService.ListDevices:input_type -> dataservice.ListDevicesRequest
	12, // 40: dataservice.DataService.UpdateDevice:input_type -> dataservice.UpdateDeviceRequest
	14, // 41: dataservice.DataService.DeleteDevice:input_type -> dataservice.DeleteDeviceRequest
	16, // 42: dataservice.DataService.CreateParameter:input_type -> dataservice.CreateParameterRequest
	18, // 43: dataservice.DataService.GetDeviceParameters:input_type -> dataservice.GetDeviceParametersRequest
	20, // 44: dataservice.DataService.GetParametersByPath:input_type -> dataservice.GetParametersByPathRequest
	22, // 45: dataservice.DataService.DeleteParameter:input_type -> dataservice.DeleteParameterRequest
	24, // 46: dataservice.DataService.CreateAlert:input_type -> dataservice.CreateAlertRequest
	26, // 47: dataservice.DataService.GetDeviceAlerts:input_type -> dataservice.GetDeviceAlertsRequest
	28, // 48: dataservice.DataService.ListAlerts:input_type -> dataservice.ListAlertsRequest
	30, // 49: dataservice.DataService.ResolveAlert:input_type -> dataservice.ResolveAlertRequest
	32, // 50: dataservice.DataService.CreateSession:input_type -> dataservice.CreateSessionRequest
	34, // 51: dataservice.DataService.GetSession:input_type -> dataservice.GetSessionRequest
	36, // 52: dataservice.DataService.UpdateSessionActivity:input_type -> dataservice.UpdateSessionActivityRequest
	38, // 53: dataservice.DataService.CloseSession:input_type -> dataservice.CloseSessionRequest
	40, // 54: dataservice.DataService.GetDeviceSessions:input_type -> dataservice.GetDeviceSessionsRequest
	43, // 55: dataservice.DataService.HealthCheck:output_type -> dataservice.HealthCheckResponse
	45, // 56: dataservice.DataService.GetStatus:output_type -> dataservice.GetStatusResponse
	5,  // 57: dataservice.DataService.CreateDevice:output_type -> dataservice.CreateDeviceResponse
	7,  // 58: dataservice.DataService.GetDevice:output_type -> dataservice.GetDeviceResponse
	9,  // 59: dataservice.DataService.GetDeviceByEndpoint:output_type -> dataservice.GetDeviceByEndpointResponse
	11, // 60: dataservice.DataService.ListDevices:output_type -> dataservice.ListDevicesResponse
	13, // 61: dataservice.DataService.UpdateDevice:output_type -> dataservice.UpdateDeviceResponse
	15, // 62: dataservice.DataService.DeleteDevice:output_type -> dataservice.DeleteDeviceResponse
	17, // 63: dataservice.DataService.CreateParameter:output_type -> dataservice.CreateParameterResponse
	19, // 64: dataservice.DataService.GetDeviceParameters:output_type -> dataservice.GetDeviceParametersResponse
	21, // 65: dataservice.DataService.GetParametersByPath:output_type -> dataservice.GetParametersByPathResponse
	23, // 66: dataservice.DataService.DeleteParameter:output_type -> dataservice.DeleteParameterResponse
	25, // 67: dataservice.DataService.CreateAlert:output_type -> dataservice.CreateAlertResponse
	27, // 68: dataservice.DataService.GetDeviceAlerts:output_type -> dataservice.GetDeviceAlertsResponse
	29, // 69: dataservice.DataService.ListAlerts:output_type -> dataservice.ListAlertsResponse
	31, // 70: dataservice.DataService.ResolveAlert:output_type -> dataservice.ResolveAlertResponse
	33, // 71: dataservice.DataService.CreateSession:output_type -> dataservice.CreateSessionResponse
	35, // 72: dataservice.DataService.GetSession:output_type -> dataservice.GetSessionResponse
	37, // 73: dataservice.DataService.UpdateSessionActivity:output_type -> dataservice.UpdateSessionActivityResponse
	39, // 74: dataservice.DataService.CloseSession:output_type -> dataservice.CloseSessionResponse
	41, // 75: dataservice.DataService.GetDeviceSessions:output_type -> dataservice.GetDeviceSessionsResponse
	55, // [55:76] is the sub-list for method output_type
	34, // [34:55] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pkg_proto_dataservice_dataservice_proto_init() }
func file_pkg_proto_dataservice_dataservice_proto_init() {
	if File_pkg_proto_dataservice_dataservice_proto != nil {
		return
	}
	file_pkg_proto_dataservice_dataservice_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_dataservice_dataservice_proto_rawDesc), len(file_pkg_proto_dataservice_dataservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_dataservice_dataservice_proto_goTypes,
		DependencyIndexes: file_pkg_proto_dataservice_dataservice_proto_depIdxs,
		MessageInfos:      file_pkg_proto_dataservice_dataservice_proto_msgTypes,
	}.Build()
	File_pkg_proto_dataservice_dataservice_proto = out.File
	file_pkg_proto_dataservice_dataservice_proto_goTypes = nil
	file_pkg_proto_dataservice_dataservice_proto_depIdxs = nil
}
