// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: connectionservice.proto

package connectionservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_GetConnection_FullMethodName             = "/connectionservice.ConnectionService/GetConnection"
	ConnectionService_GetConnectionStatus_FullMethodName       = "/connectionservice.ConnectionService/GetConnectionStatus"
	ConnectionService_RegisterServiceDependency_FullMethodName = "/connectionservice.ConnectionService/RegisterServiceDependency"
	ConnectionService_RefreshConnections_FullMethodName        = "/connectionservice.ConnectionService/RefreshConnections"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectionService manages gRPC connections between OpenUSP services
type ConnectionServiceClient interface {
	// GetConnection returns a healthy connection to the specified service
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error)
	// GetConnectionStatus returns status of all managed connections
	GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error)
	// RegisterServiceDependency registers a service dependency for proactive connection management
	RegisterServiceDependency(ctx context.Context, in *RegisterDependencyRequest, opts ...grpc.CallOption) (*RegisterDependencyResponse, error)
	// RefreshConnections forces refresh of connections to a service
	RefreshConnections(ctx context.Context, in *RefreshConnectionsRequest, opts ...grpc.CallOption) (*RefreshConnectionsResponse, error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionResponse)
	err := c.cc.Invoke(ctx, ConnectionService_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionStatusResponse)
	err := c.cc.Invoke(ctx, ConnectionService_GetConnectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) RegisterServiceDependency(ctx context.Context, in *RegisterDependencyRequest, opts ...grpc.CallOption) (*RegisterDependencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDependencyResponse)
	err := c.cc.Invoke(ctx, ConnectionService_RegisterServiceDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) RefreshConnections(ctx context.Context, in *RefreshConnectionsRequest, opts ...grpc.CallOption) (*RefreshConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshConnectionsResponse)
	err := c.cc.Invoke(ctx, ConnectionService_RefreshConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
//
// ConnectionService manages gRPC connections between OpenUSP services
type ConnectionServiceServer interface {
	// GetConnection returns a healthy connection to the specified service
	GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error)
	// GetConnectionStatus returns status of all managed connections
	GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error)
	// RegisterServiceDependency registers a service dependency for proactive connection management
	RegisterServiceDependency(context.Context, *RegisterDependencyRequest) (*RegisterDependencyResponse, error)
	// RefreshConnections forces refresh of connections to a service
	RefreshConnections(context.Context, *RefreshConnectionsRequest) (*RefreshConnectionsResponse, error)
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedConnectionServiceServer) GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectionStatus not implemented")
}
func (UnimplementedConnectionServiceServer) RegisterServiceDependency(context.Context, *RegisterDependencyRequest) (*RegisterDependencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServiceDependency not implemented")
}
func (UnimplementedConnectionServiceServer) RefreshConnections(context.Context, *RefreshConnectionsRequest) (*RefreshConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshConnections not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_GetConnectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetConnectionStatus(ctx, req.(*GetConnectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_RegisterServiceDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).RegisterServiceDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_RegisterServiceDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).RegisterServiceDependency(ctx, req.(*RegisterDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_RefreshConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).RefreshConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_RefreshConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).RefreshConnections(ctx, req.(*RefreshConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connectionservice.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnection",
			Handler:    _ConnectionService_GetConnection_Handler,
		},
		{
			MethodName: "GetConnectionStatus",
			Handler:    _ConnectionService_GetConnectionStatus_Handler,
		},
		{
			MethodName: "RegisterServiceDependency",
			Handler:    _ConnectionService_RegisterServiceDependency_Handler,
		},
		{
			MethodName: "RefreshConnections",
			Handler:    _ConnectionService_RefreshConnections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectionservice.proto",
}
