// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: connectionservice.proto

package connectionservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetConnectionRequest requests a connection to a specific service
type GetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                                  // Name of the service to connect to
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional metadata for connection selection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_connectionservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetConnectionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetConnectionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetConnectionResponse returns connection information
type GetConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                                            // Whether connection was obtained successfully
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error message if success is false
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                                                                               // Target address of the connection
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                                                                 // Current connection state
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // Connection creation timestamp
	LastUsed      int64                  `protobuf:"varint,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`                                                          // Last usage timestamp
	ErrorCount    int32                  `protobuf:"varint,7,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`                                                    // Number of errors on this connection
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Connection metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionResponse) Reset() {
	*x = GetConnectionResponse{}
	mi := &file_connectionservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionResponse) ProtoMessage() {}

func (x *GetConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionResponse) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetConnectionResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetConnectionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetConnectionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetConnectionResponse) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *GetConnectionResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *GetConnectionResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetConnectionStatusRequest requests status of connections
type GetConnectionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Optional: specific service name, empty for all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatusRequest) Reset() {
	*x = GetConnectionStatusRequest{}
	mi := &file_connectionservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusRequest) ProtoMessage() {}

func (x *GetConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// GetConnectionStatusResponse returns connection status information
type GetConnectionStatusResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Services      map[string]*ServiceStatus `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Status by service name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatusResponse) Reset() {
	*x = GetConnectionStatusResponse{}
	mi := &file_connectionservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusResponse) ProtoMessage() {}

func (x *GetConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectionStatusResponse) GetServices() map[string]*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

// ServiceStatus represents the status of connections to a specific service
type ServiceStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServiceName        string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                       // Name of the service
	TotalConnections   int32                  `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`       // Total number of connections
	HealthyConnections int32                  `protobuf:"varint,3,opt,name=healthy_connections,json=healthyConnections,proto3" json:"healthy_connections,omitempty"` // Number of healthy connections
	CircuitOpen        bool                   `protobuf:"varint,4,opt,name=circuit_open,json=circuitOpen,proto3" json:"circuit_open,omitempty"`                      // Whether circuit breaker is open
	IsHealthy          bool                   `protobuf:"varint,5,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`                            // Overall health status
	LastHealthCheck    int64                  `protobuf:"varint,6,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`        // Last health check timestamp
	FailureCount       int32                  `protobuf:"varint,7,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`                   // Number of consecutive failures
	Connections        []*ConnectionDetail    `protobuf:"bytes,8,rep,name=connections,proto3" json:"connections,omitempty"`                                          // Individual connection details
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_connectionservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceStatus) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *ServiceStatus) GetHealthyConnections() int32 {
	if x != nil {
		return x.HealthyConnections
	}
	return 0
}

func (x *ServiceStatus) GetCircuitOpen() bool {
	if x != nil {
		return x.CircuitOpen
	}
	return false
}

func (x *ServiceStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *ServiceStatus) GetLastHealthCheck() int64 {
	if x != nil {
		return x.LastHealthCheck
	}
	return 0
}

func (x *ServiceStatus) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ServiceStatus) GetConnections() []*ConnectionDetail {
	if x != nil {
		return x.Connections
	}
	return nil
}

// ConnectionDetail provides details about a specific connection
type ConnectionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                             // Connection index in pool
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                            // Target address
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                              // gRPC connection state
	LastUsed      int64                  `protobuf:"varint,4,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`       // Last usage timestamp
	ErrorCount    int32                  `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"` // Number of errors
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // Creation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionDetail) Reset() {
	*x = ConnectionDetail{}
	mi := &file_connectionservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionDetail) ProtoMessage() {}

func (x *ConnectionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionDetail.ProtoReflect.Descriptor instead.
func (*ConnectionDetail) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectionDetail) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ConnectionDetail) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ConnectionDetail) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectionDetail) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *ConnectionDetail) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ConnectionDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// RegisterDependencyRequest registers a service dependency
type RegisterDependencyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                  // Name of the service that has the dependency
	DependsOnService string                 `protobuf:"bytes,2,opt,name=depends_on_service,json=dependsOnService,proto3" json:"depends_on_service,omitempty"` // Name of the service being depended on
	MinConnections   int32                  `protobuf:"varint,3,opt,name=min_connections,json=minConnections,proto3" json:"min_connections,omitempty"`        // Minimum number of connections to maintain
	MaxConnections   int32                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`        // Maximum number of connections to maintain
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterDependencyRequest) Reset() {
	*x = RegisterDependencyRequest{}
	mi := &file_connectionservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDependencyRequest) ProtoMessage() {}

func (x *RegisterDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDependencyRequest.ProtoReflect.Descriptor instead.
func (*RegisterDependencyRequest) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDependencyRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterDependencyRequest) GetDependsOnService() string {
	if x != nil {
		return x.DependsOnService
	}
	return ""
}

func (x *RegisterDependencyRequest) GetMinConnections() int32 {
	if x != nil {
		return x.MinConnections
	}
	return 0
}

func (x *RegisterDependencyRequest) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

// RegisterDependencyResponse confirms dependency registration
type RegisterDependencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether registration was successful
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error message if success is false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDependencyResponse) Reset() {
	*x = RegisterDependencyResponse{}
	mi := &file_connectionservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDependencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDependencyResponse) ProtoMessage() {}

func (x *RegisterDependencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDependencyResponse.ProtoReflect.Descriptor instead.
func (*RegisterDependencyResponse) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterDependencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDependencyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RefreshConnectionsRequest requests connection refresh for a service
type RefreshConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`        // Name of the service to refresh connections for
	ForceRecreate bool                   `protobuf:"varint,2,opt,name=force_recreate,json=forceRecreate,proto3" json:"force_recreate,omitempty"` // Whether to force recreation of all connections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshConnectionsRequest) Reset() {
	*x = RefreshConnectionsRequest{}
	mi := &file_connectionservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConnectionsRequest) ProtoMessage() {}

func (x *RefreshConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConnectionsRequest.ProtoReflect.Descriptor instead.
func (*RefreshConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshConnectionsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RefreshConnectionsRequest) GetForceRecreate() bool {
	if x != nil {
		return x.ForceRecreate
	}
	return false
}

// RefreshConnectionsResponse confirms connection refresh
type RefreshConnectionsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                       // Whether refresh was successful
	Error                string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                            // Error message if success is false
	ConnectionsRefreshed int32                  `protobuf:"varint,3,opt,name=connections_refreshed,json=connectionsRefreshed,proto3" json:"connections_refreshed,omitempty"` // Number of connections refreshed
	ConnectionsCreated   int32                  `protobuf:"varint,4,opt,name=connections_created,json=connectionsCreated,proto3" json:"connections_created,omitempty"`       // Number of new connections created
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RefreshConnectionsResponse) Reset() {
	*x = RefreshConnectionsResponse{}
	mi := &file_connectionservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConnectionsResponse) ProtoMessage() {}

func (x *RefreshConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectionservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConnectionsResponse.ProtoReflect.Descriptor instead.
func (*RefreshConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_connectionservice_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshConnectionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshConnectionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RefreshConnectionsResponse) GetConnectionsRefreshed() int32 {
	if x != nil {
		return x.ConnectionsRefreshed
	}
	return 0
}

func (x *RefreshConnectionsResponse) GetConnectionsCreated() int32 {
	if x != nil {
		return x.ConnectionsCreated
	}
	return 0
}

var File_connectionservice_proto protoreflect.FileDescriptor

const file_connectionservice_proto_rawDesc = "" +
	"\n" +
	"\x17connectionservice.proto\x12\x11connectionservice\"\xc9\x01\n" +
	"\x14GetConnectionRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12Q\n" +
	"\bmetadata\x18\x02 \x03(\v25.connectionservice.GetConnectionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\x15GetConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tlast_used\x18\x06 \x01(\x03R\blastUsed\x12\x1f\n" +
	"\verror_count\x18\a \x01(\x05R\n" +
	"errorCount\x12R\n" +
	"\bmetadata\x18\b \x03(\v26.connectionservice.GetConnectionResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x1aGetConnectionStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xd6\x01\n" +
	"\x1bGetConnectionStatusResponse\x12X\n" +
	"\bservices\x18\x01 \x03(\v2<.connectionservice.GetConnectionStatusResponse.ServicesEntryR\bservices\x1a]\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .connectionservice.ServiceStatusR\x05value:\x028\x01\"\xea\x02\n" +
	"\rServiceStatus\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12+\n" +
	"\x11total_connections\x18\x02 \x01(\x05R\x10totalConnections\x12/\n" +
	"\x13healthy_connections\x18\x03 \x01(\x05R\x12healthyConnections\x12!\n" +
	"\fcircuit_open\x18\x04 \x01(\bR\vcircuitOpen\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x05 \x01(\bR\tisHealthy\x12*\n" +
	"\x11last_health_check\x18\x06 \x01(\x03R\x0flastHealthCheck\x12#\n" +
	"\rfailure_count\x18\a \x01(\x05R\ffailureCount\x12E\n" +
	"\vconnections\x18\b \x03(\v2#.connectionservice.ConnectionDetailR\vconnections\"\xb3\x01\n" +
	"\x10ConnectionDetail\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\tlast_used\x18\x04 \x01(\x03R\blastUsed\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x05R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xbe\x01\n" +
	"\x19RegisterDependencyRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12,\n" +
	"\x12depends_on_service\x18\x02 \x01(\tR\x10dependsOnService\x12'\n" +
	"\x0fmin_connections\x18\x03 \x01(\x05R\x0eminConnections\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05R\x0emaxConnections\"L\n" +
	"\x1aRegisterDependencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"e\n" +
	"\x19RefreshConnectionsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0eforce_recreate\x18\x02 \x01(\bR\rforceRecreate\"\xb2\x01\n" +
	"\x1aRefreshConnectionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\x15connections_refreshed\x18\x03 \x01(\x05R\x14connectionsRefreshed\x12/\n" +
	"\x13connections_created\x18\x04 \x01(\x05R\x12connectionsCreated2\xda\x03\n" +
	"\x11ConnectionService\x12b\n" +
	"\rGetConnection\x12'.connectionservice.GetConnectionRequest\x1a(.connectionservice.GetConnectionResponse\x12t\n" +
	"\x13GetConnectionStatus\x12-.connectionservice.GetConnectionStatusRequest\x1a..connectionservice.GetConnectionStatusResponse\x12x\n" +
	"\x19RegisterServiceDependency\x12,.connectionservice.RegisterDependencyRequest\x1a-.connectionservice.RegisterDependencyResponse\x12q\n" +
	"\x12RefreshConnections\x12,.connectionservice.RefreshConnectionsRequest\x1a-.connectionservice.RefreshConnectionsResponseB%Z#openusp/pkg/proto/connectionserviceb\x06proto3"

var (
	file_connectionservice_proto_rawDescOnce sync.Once
	file_connectionservice_proto_rawDescData []byte
)

func file_connectionservice_proto_rawDescGZIP() []byte {
	file_connectionservice_proto_rawDescOnce.Do(func() {
		file_connectionservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connectionservice_proto_rawDesc), len(file_connectionservice_proto_rawDesc)))
	})
	return file_connectionservice_proto_rawDescData
}

var file_connectionservice_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_connectionservice_proto_goTypes = []any{
	(*GetConnectionRequest)(nil),        // 0: connectionservice.GetConnectionRequest
	(*GetConnectionResponse)(nil),       // 1: connectionservice.GetConnectionResponse
	(*GetConnectionStatusRequest)(nil),  // 2: connectionservice.GetConnectionStatusRequest
	(*GetConnectionStatusResponse)(nil), // 3: connectionservice.GetConnectionStatusResponse
	(*ServiceStatus)(nil),               // 4: connectionservice.ServiceStatus
	(*ConnectionDetail)(nil),            // 5: connectionservice.ConnectionDetail
	(*RegisterDependencyRequest)(nil),   // 6: connectionservice.RegisterDependencyRequest
	(*RegisterDependencyResponse)(nil),  // 7: connectionservice.RegisterDependencyResponse
	(*RefreshConnectionsRequest)(nil),   // 8: connectionservice.RefreshConnectionsRequest
	(*RefreshConnectionsResponse)(nil),  // 9: connectionservice.RefreshConnectionsResponse
	nil,                                 // 10: connectionservice.GetConnectionRequest.MetadataEntry
	nil,                                 // 11: connectionservice.GetConnectionResponse.MetadataEntry
	nil,                                 // 12: connectionservice.GetConnectionStatusResponse.ServicesEntry
}
var file_connectionservice_proto_depIdxs = []int32{
	10, // 0: connectionservice.GetConnectionRequest.metadata:type_name -> connectionservice.GetConnectionRequest.MetadataEntry
	11, // 1: connectionservice.GetConnectionResponse.metadata:type_name -> connectionservice.GetConnectionResponse.MetadataEntry
	12, // 2: connectionservice.GetConnectionStatusResponse.services:type_name -> connectionservice.GetConnectionStatusResponse.ServicesEntry
	5,  // 3: connectionservice.ServiceStatus.connections:type_name -> connectionservice.ConnectionDetail
	4,  // 4: connectionservice.GetConnectionStatusResponse.ServicesEntry.value:type_name -> connectionservice.ServiceStatus
	0,  // 5: connectionservice.ConnectionService.GetConnection:input_type -> connectionservice.GetConnectionRequest
	2,  // 6: connectionservice.ConnectionService.GetConnectionStatus:input_type -> connectionservice.GetConnectionStatusRequest
	6,  // 7: connectionservice.ConnectionService.RegisterServiceDependency:input_type -> connectionservice.RegisterDependencyRequest
	8,  // 8: connectionservice.ConnectionService.RefreshConnections:input_type -> connectionservice.RefreshConnectionsRequest
	1,  // 9: connectionservice.ConnectionService.GetConnection:output_type -> connectionservice.GetConnectionResponse
	3,  // 10: connectionservice.ConnectionService.GetConnectionStatus:output_type -> connectionservice.GetConnectionStatusResponse
	7,  // 11: connectionservice.ConnectionService.RegisterServiceDependency:output_type -> connectionservice.RegisterDependencyResponse
	9,  // 12: connectionservice.ConnectionService.RefreshConnections:output_type -> connectionservice.RefreshConnectionsResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_connectionservice_proto_init() }
func file_connectionservice_proto_init() {
	if File_connectionservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connectionservice_proto_rawDesc), len(file_connectionservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connectionservice_proto_goTypes,
		DependencyIndexes: file_connectionservice_proto_depIdxs,
		MessageInfos:      file_connectionservice_proto_msgTypes,
	}.Build()
	File_connectionservice_proto = out.File
	file_connectionservice_proto_goTypes = nil
	file_connectionservice_proto_depIdxs = nil
}
